frontendNextWebApp:
  component: '@sls-next/serverless-component@1.19.0-alpha.31'
  custom:
    stage: ${opt:stage, self:provider.stage}
  inputs:
    bucketName: nextjs-serverless-boilerplate-bucket
    name:
      defaultLambda: ${self:custom.stage}-DefaultLambda
      apiLambda: ${self:custom.stage}-ApiLambda
      imageLambda: ${self:custom.stage}-ImageLambda